### ISSUE TITLE
Auto-label new Issues with TRIAGE label using GH Actions

### ISSUE THREAD

**Issue by Azaya89** [holoviz/hvplot#1581]
#### Is your feature request related to a problem? Please describe.

Currently, newly opened issues are not automatically labeled unless the issue is created via the web UI using the ISSUE_TEMPLATE file. This causes some issues opened from GitHub Projects or the GH CLI to go unlabeled, making triaging more difficult.

#### Describe the solution you'd like

I propose adding a simple GitHub Actions workflow that automatically assigns the `TRIAGE` label to all newly opened issues. This ensures that every new issue, regardless of how it is created, gets a TRIAGE label immediately

#### Describe alternatives you've considered

- Continuing with the current system that still leaves the highlighted problems.
- Manually adding the `TRIAGE` label, but this is easy to forget and doesn’t scale well.

#### Additional context
A minimal [tested example](https://github.com/Azaya89/hvplot/issues/4) of the workflow is available and works as expected:
```yaml
name: Auto-label new issues with "triage"

on:
  issues:
    types: [opened]

jobs:
  add-triage-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add TRIAGE label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: TRIAGE
```
