### ISSUE TITLE
Could holoviz adopt more of a "release early, release often" approach for conda-forge?

### ISSUE THREAD

**Issue by rsignell-usgs** [holoviz/hvplot#324]
@jbednar, I'm going to be giving a Pangeo tutorial next week at the Integrated Ocean Observing System code sprint in Ann Arbor for about 40 people, and several notebooks with HoloViz tools will be featured.   

Currently the `environment.yml` to get the needed HoloViz functionality looks like this:

```yaml
 channels:
  - conda-forge
dependencies:
  - cartopy
  - fsspec
  - pyviz/label/dev::hvplot
  - pyviz/label/dev::holoviews
  - pyviz/label/dev::panel
  - pyviz/label/dev::datashader
  - metpy
  - numpy
  - xarray
  - pip
  - pip:
    - git+https://github.com/pyviz/geoviews.git
```
Obviously getting a bunch of stuff from dev channels and geoviews from master does not exactly convey confidence to HoloViz newcomers.  

I realize that all these packages change rapidly and have inter-dependencies, but could a   "release often, release early" approach with the standard conda-forge channel be adopted as a solution?   Are the released packages really that much more stable than the dev channel packages?  

@ocefpaf has long advocated for this approach, and I think it would really help boost community use of the HoloViz suite.
